# Generated by Django 3.0.7 on 2020-06-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel_id', models.CharField(default='channelid', max_length=200)),
                ('picture', models.ImageField(default='artists/default.jpg', upload_to='artists')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_file', models.FileField(upload_to='songs')),
                ('thumbnail', models.ImageField(default='songs/default.jpg', upload_to='songthumbnails')),
                ('plays', models.IntegerField(default=0)),
                ('video_id', models.CharField(default='video_id', max_length=50)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('artistname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artistname', to='music.Artist')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
